# Generated by Django 6.0.3 on 2026-03-25 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('meta_title', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.TextField(blank=True)),
                ('meta_keywords', models.CharField(blank=True, max_length=500)),
                ('canonical_url', models.URLField(blank=True)),
                ('og_title', models.CharField(blank=True, max_length=255)),
                ('og_description', models.TextField(blank=True)),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='seo/og/')),
                ('robots', models.CharField(default='index,follow', max_length=100)),
                ('title', models.CharField(max_length=220)),
                ('summary', models.TextField(blank=True)),
                ('overview', models.TextField(blank=True)),
                ('curriculum_details', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='programs/')),
            ],
            options={
                'verbose_name': 'Program Page',
                'verbose_name_plural': 'Program Pages',
            },
        ),
        migrations.CreateModel(
            name='SchoolDivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('meta_title', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.TextField(blank=True)),
                ('meta_keywords', models.CharField(blank=True, max_length=500)),
                ('canonical_url', models.URLField(blank=True)),
                ('og_title', models.CharField(blank=True, max_length=255)),
                ('og_description', models.TextField(blank=True)),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='seo/og/')),
                ('robots', models.CharField(default='index,follow', max_length=100)),
                ('title', models.CharField(max_length=220)),
                ('summary', models.TextField(blank=True)),
                ('overview', models.TextField(blank=True)),
                ('teaching_approach', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='divisions/')),
            ],
            options={
                'verbose_name': 'School Division',
                'verbose_name_plural': 'School Divisions',
            },
        ),
        migrations.CreateModel(
            name='SubjectArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='CSS class for icon', max_length=50)),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='academics.schooldivision')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='academics.programpage')),
            ],
            options={
                'verbose_name': 'Subject Area',
                'verbose_name_plural': 'Subject Areas',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
    ]
