# Generated by Django 6.0.3 on 2026-03-25 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Admission FAQ',
                'verbose_name_plural': 'Admission FAQs',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdmissionInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('child_name', models.CharField(max_length=150)),
                ('child_age', models.PositiveIntegerField()),
                ('class_applied_for', models.CharField(max_length=100)),
                ('message', models.TextField(blank=True)),
                ('is_reviewed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Admission Inquiry',
                'verbose_name_plural': 'Admission Inquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdmissionPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('meta_title', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.TextField(blank=True)),
                ('meta_keywords', models.CharField(blank=True, max_length=500)),
                ('canonical_url', models.URLField(blank=True)),
                ('og_title', models.CharField(blank=True, max_length=255)),
                ('og_description', models.TextField(blank=True)),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='seo/og/')),
                ('robots', models.CharField(default='index,follow', max_length=100)),
                ('title', models.CharField(max_length=220)),
                ('summary', models.TextField(blank=True)),
                ('intro_text', models.TextField(blank=True, help_text='Welcome text for the admissions page.')),
                ('fee_notes', models.TextField(blank=True, help_text='Information about fees or how to request a fee schedule.')),
                ('contact_notes', models.TextField(blank=True, help_text='Extra contact info or office hours.')),
            ],
            options={
                'verbose_name': 'Admission Page Content',
                'verbose_name_plural': 'Admission Page Content',
            },
        ),
        migrations.CreateModel(
            name='AdmissionRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('item', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Admission Requirement',
                'verbose_name_plural': 'Admission Requirements',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdmissionStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('icon', models.CharField(blank=True, help_text='CSS class for icon', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Admission Step',
                'verbose_name_plural': 'Admission Steps',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
    ]
